### ISSUE TITLE
[Rewrite]: The Source

### ISSUE THREAD

**Issue by Anish-Shobith** [Anish-Shobith/mdn-api#2]
JavaScript Docs

Why? 
The current Api is not parsing few data properly this is why , I have decided to Rewrite this by trying a different Approch!

**Comment by KhafraDev** [comment]
@Anish-Shobith MDN (Kuma to be exact) offers a really nice API to search: 
`https://developer.mozilla.org/api/v1/search/en-US?q=[query here]`
As an example, to search for "Array" it would be https://developer.mozilla.org/api/v1/search/en-US?q=array (multi-worded searches should be joined by a +).

**Comment by Anish-Shobith** [comment]
Thanks a lot ❤ @KhafraDev , I will look into it very soon
